# Generated by Django 3.0 on 2019-12-04 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intervalo_treinos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Regiao_corporal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tempo_repeticao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dia_semana', models.CharField(max_length=100)),
                ('intervalo_treinos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Intervalo_treinos')),
                ('regiao', models.ManyToManyField(to='core.Regiao_corporal')),
                ('tempo_repaticao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tempo_repeticao')),
            ],
        ),
    ]
